export const GET_ALL_DISTRICTS = "GET_ALL_DISTRICTS";
export const GET_ALL_DISTRICTS_SUCCESS = "GET_ALL_DISTRICTS_SUCCESS";
export const GET_ALL_DISTRICTS_FAILED = "GET_ALL_DISTRICTS_FAILED";

export const GET_DISTRICT = "GET_DISTRICT";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_FAILED = "GET_DISTRICT_FAILED";

export const ADD_DISTRICT = "ADD_DISTRICT";
export const ADD_DISTRICT_SUCCESS = "ADD_DISTRICT_SUCCESS";
export const ADD_DISTRICT_FAILED = "ADD_DISTRICT_FAILED";

export const UPDATE_DISTRICT = "UPDATE_DISTRICT";
export const UPDATE_DISTRICT_SUCCESS = "UPDATE_DISTRICT_SUCCESS";
export const UPDATE_DISTRICT_FAILED = "UPDATE_DISTRICT_FAILED";

export const DELETE_DISTRICT = "DELETE_DISTRICT";
export const DELETE_DISTRICT_SUCCESS = "DELETE_DISTRICT_SUCCESS";
export const DELETE_DISTRICT_FAILED = "DELETE_DISTRICT_FAILED";

export const SEARCH_DISTRICT = "SEARCH_DISTRICT";
export const SEARCH_DISTRICT_SUCCESS = "SEARCH_DISTRICT_SUCCESS";
export const SEARCH_DISTRICT_FAILED = "SEARCH_DISTRICT_FAILED";