export const GET_ALL_PROMOTIONS = "GET_ALL_PROMOTIONS";
export const GET_ALL_PROMOTIONS_SUCCESS = "GET_ALL_PROMOTIONS_SUCCESS";
export const GET_ALL_PROMOTIONS_FAILED = "GET_ALL_PROMOTIONS_FAILED";

export const GET_PROMOTION = "GET_PROMOTION";
export const GET_PROMOTION_SUCCESS = "GET_PROMOTION_SUCCESS";
export const GET_PROMOTION_FAILED = "GET_PROMOTION_FAILED";

export const ADD_PROMOTION = "ADD_PROMOTION";
export const ADD_PROMOTION_SUCCESS = "ADD_PROMOTION_SUCCESS";
export const ADD_PROMOTION_FAILED = "ADD_PROMOTION_FAILED";

export const UPDATE_PROMOTION = "UPDATE_PROMOTION";
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS";
export const UPDATE_PROMOTION_FAILED = "UPDATE_PROMOTION_FAILED";

export const DELETE_PROMOTION = "DELETE_PROMOTION";
export const DELETE_PROMOTION_SUCCESS = "DELETE_PROMOTION_SUCCESS";
export const DELETE_PROMOTION_FAILED = "DELETE_PROMOTION_FAILED";

export const SEARCH_PROMOTION = "SEARCH_PROMOTION";
export const SEARCH_PROMOTION_SUCCESS = "SEARCH_PROMOTION_SUCCESS";
export const SEARCH_PROMOTION_FAILED = "SEARCH_PROMOTION_FAILED";